Fix interpretation of null CStr
aQaTL/sane-scan pull request #1
Opened 2022-01-05 21:48 UTC by sunsided

Hey! When using the library I stumbled upon an issue with an old CanoScan LIDE 20 where `get_options()` would segfault due to a `NULL` option name.

I added a wrapper method that returns an empty `CString` in these cases:

```
DeviceOption { option_idx: 1, name: "", title: "Scan Mode", desc: "", type_: Group, unit: None, size: 4, cap: (empty), constraint: None }
```

2022-01-05 22:58 UTC, aQaTL requested changes
Hey! Thanks for contributing, I appreciate it a lot :smile: 

Looks good overall. I only have a few nits, all about my preferred code style :) 

Thanks

2022-01-05 22:58 UTC, aQaTL commented on src/lib.rs
> +		CString::new("").expect("CString::new failed")
Use CString::default() get an empty string. It also allows us to avoid having to have the `expect`. 

```suggestion
		CString::default()
```

2022-01-05 22:58 UTC, aQaTL commented on src/lib.rs
> +	if ptr == std::ptr::null() {
```suggestion
	if ptr.is_null() {
```

2022-01-05 22:58 UTC, aQaTL commented on src/lib.rs
> +fn to_cstring_safe(ptr: *const std::os::raw::c_char) -> CString {
I'd name this `cstring_from_ptr` - I don't see a reason to add the `safe` suffix (like, any function should be safe or marked "unsafe" otherwise)

2022-01-05 22:58 UTC, aQaTL commented on src/lib.rs
> +		CString::new("").expect("CString::new failed")
One more thing, just my code style preference. Please `return` here if the pointer is null and drop the `else` branch, so it's goes like

```
if not_good {
    return default_value;
}
happy_path_continued..
```

2022-01-07 15:19 UTC, sunsided commented
Got you! I also like to add that your "preferred code style" is simply better than what I did there. 🙈😅

2022-01-07 19:15 UTC, merged

2022-01-07 19:15 UTC, aQaTL commented
Thanks!